
- hosts: all
  tasks:
  - name: set the hostname
    hostname:
      name: "{{ hostname }}"
    become: yes
  - name: stop verium miner
    service: name=veriumminer state=stopped
    become: yes
  - name: template for miner script
    vars:
      numcores_use: "{{ numcores_to_use }}"
    template:
      src: files/run_miner.j2
      dest: /home/orangepi/veriumMiner/run_miner.sh
      owner: orangepi
      group: orangepi
      mode: "u=rwx"

  - name: restart verium miner
    service: name=veriumminer state=started
    become: yes
